import request from './request'

export const startGame = (data) => request.post('/game/start/auth', data)
export const getGameInfo = (params) => request.get('/game/info/auth', { params })
export const nextStage = (data) => request.post('/game/nextStage/auth', data)
export const nextSpeaker = (data) => request.post('/game/nextSpeaker/auth', data)
export const nextLastWordSpeaker = (data) => request.post('/game/nextLastWordSpeaker/auth', data)
export const gameRecord = (params) => request.get('/game/record/auth', { params })
export const checkPlayer = (data) => request.post('/game/checkPlayer/auth', data)
export const assaultPlayer = (data) => request.post('/game/assaultPlayer/auth', data)
export const antidotePlayer = (data) => request.post('/game/antidotePlayer/auth', data)
export const votePlayer = (data) => request.post('/game/votePlayer/auth', data)
export const poisonPlayer = (data) => request.post('/game/poisonPlayer/auth', data)
export const shootPlayer = (data) => request.post('/game/shootPlayer/auth', data)
export const gameResult = (params) => request.get('/game/result/auth', { params })
export const gameDestroy = (data) => request.post('/game/destroy/auth', data)
export const gameAgain = (data) => request.post('/game/again/auth', data)
export const restartGame = (data) => request.post('/game/restart/auth', data)
export const obGame = (data) => request.post('/game/ob/auth', data)
export const getGameSettings = (params) => request.get('/game/settings/auth', { params })
export const getRecentGame = () => request.get('/game/recent/auth')
export const getChatHistory = (params) => request.get('/game/chatHistory/auth', { params })
